// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import pagetemplate "github.com/Pergamene/project-spiderweb-service/internal/models/pagetemplate"

// PageTemplateStore is an autogenerated mock type for the PageTemplateStore type
type PageTemplateStore struct {
	mock.Mock
}

// GetPageTemplate provides a mock function with given fields: pageTemplateGUID
func (_m *PageTemplateStore) GetPageTemplate(pageTemplateGUID string) (pagetemplate.PageTemplate, error) {
	ret := _m.Called(pageTemplateGUID)

	var r0 pagetemplate.PageTemplate
	if rf, ok := ret.Get(0).(func(string) pagetemplate.PageTemplate); ok {
		r0 = rf(pageTemplateGUID)
	} else {
		r0 = ret.Get(0).(pagetemplate.PageTemplate)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(pageTemplateGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
