// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import appuser "github.com/Pergamene/project-spiderweb-service/internal/models/appuser"
import mock "github.com/stretchr/testify/mock"

// UserStore is an autogenerated mock type for the UserStore type
type UserStore struct {
	mock.Mock
}

// GetUser provides a mock function with given fields: userGUID
func (_m *UserStore) GetUser(userGUID string) (appuser.User, error) {
	ret := _m.Called(userGUID)

	var r0 appuser.User
	if rf, ok := ret.Get(0).(func(string) appuser.User); ok {
		r0 = rf(userGUID)
	} else {
		r0 = ret.Get(0).(appuser.User)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(userGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
