// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"

import version "github.com/Pergamene/project-spiderweb-service/internal/models/version"

// VersionStore is an autogenerated mock type for the VersionStore type
type VersionStore struct {
	mock.Mock
}

// GetVersion provides a mock function with given fields: versionGUID
func (_m *VersionStore) GetVersion(versionGUID string) (version.Version, error) {
	ret := _m.Called(versionGUID)

	var r0 version.Version
	if rf, ok := ret.Get(0).(func(string) version.Version); ok {
		r0 = rf(versionGUID)
	} else {
		r0 = ret.Get(0).(version.Version)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(versionGUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
